### ISSUE TITLE
Přidat možnost mít v YAML konfiguraci v `extra_files` binární soubory

### ISSUE THREAD

**Issue by encukou** [encukou/freezeyt#126]
Ideálně buď před [base64](https://docs.python.org/3/library/base64.html) nebo zkopírování existujícího souboru:
```yaml
extra_files:
    config.dat:
        base64: "YWJjZAASNA=="
    config2.dat:
        copy_from: included/config2.dat
```
